# Generated by Django 3.2.5 on 2021-08-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smithy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='pub_date',
        ),
    ]
