# Generated by Django 3.2.5 on 2021-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smithy', '0002_remove_userinput_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=20)),
                ('sim', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Userinput',
        ),
    ]
